services:
  api:
    image: odata.demo.api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=OdataDemoDb;User=sa;Password=Your_password123;TrustServerCertificate=True;MultipleActiveResultSets=true

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: odata_demo_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: